module.exports = [
  {
    num: 001,
    name: "Bulbizarre",
    types: ["Plante", "Poison"],
    taille: 0.7,
    poids: 6.9,
    attaque: 49,
    defense: 49,
    image: "https://www.pokebip.com/pokedex/images/sugimori/1.png",
  },
  {
    num: 002,
    name: "Herbizarre",
    types: ["Plante", "Poison"],
    taille: 1.0,
    poids: 13.0,
    attaque: 62,
    defense: 63,
    image: "https://www.pokebip.com/pokedex/images/sugimori/2.png",
  },
  {
    num: 003,
    name: "Florizarre",
    types: ["Plante", "Poison"],
    taille: 2.0,
    poids: 100.0,
    attaque: 82,
    defense: 83,
    image: "https://www.pokebip.com/pokedex/images/sugimori/3.png",
  },
  {
    num: 004,
    name: "Salameche",
    types: ["Feu"],
    taille: 0.6,
    poids: 8.5,
    attaque: 52,
    defense: 43,
    image: "https://www.pokebip.com/pokedex/images/sugimori/4.png",
  },
];
